apiVersion: v1
kind: Service
metadata:
  name: {{ include "rules-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/"
  labels:
    app.kubernetes.io/name: {{ include "rules-exporter.name" . }}
    helm.sh/chart: {{ include "rules-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rules-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
