# Default values for rules-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: us.gcr.io/unity-cs-devops-gcr-prd/prometheus-rules-exporter
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

urlInventory: https://inventory.internal.unity3d.com
urlPrometheus: 

resources: {}

nodeSelector:
  product: devops

tolerations:
  - effect: NoSchedule
    key: product
    operator: Equal
    value: devops

affinity: {}

env: {}